### ISSUE TITLE
some fixes in this fork https://github.com/devloic/AzuraCast-Player

### ISSUE THREAD

**Issue by devloic** [PeWe79/AzuraCast-Player#1]
Hi,

thanks for your code.

I added some little fixes to AzuraCast-Player you might find relevant:
- fixed some scss deprecations 
- added "serve": "http-server . -p 8484 -a localhost" script to package.json ( webpack serve might be better but my understanding on how to migrate webpack.config.js is limited)
- added @error="$event.target.src=apiBaseUrl()+'/static/img/generic_song.jpg' so if a azuracast playlist has no image it will use the default azuracast icon ie generic_song.jpg
- changed "toText" filter so it doesn't strip accents for languages that use accents or umlaut (ex:  è, é, ê, ë...)
- changed .jpg to .png filename which was needed in my specific setup ( might be worse finding a trick to make detection automatic or add it as config parameter)

plans:
- add the player to the azuracast docker image
- make it work for a single station (no sidebar) or multiple stations (sidebar)

**Comment by PeWe79** [comment]
Hi @devloic,

Thanks if you like this code and for add future for this code. This code is free for developing and add some future.

**Comment by devloic** [comment]
It is using Vue 2 right ? would it be complicated to migrate it to Vue 3 ?

**Comment by PeWe79** [comment]
Yes with Vue 2. Actually not to be complicated if want to migrating to Vue 3 if with current future.
